# Generated by Django 2.1 on 2018-09-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_login_device',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='当前登录设备'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_login_ip',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='当前登录IP'),
        ),
        migrations.AddField(
            model_name='account',
            name='email_binding_flag',
            field=models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=256, null=True, verbose_name='邮箱绑定标志'),
        ),
        migrations.AddField(
            model_name='account',
            name='head_img',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='account',
            name='qq_binding_flag',
            field=models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=256, null=True, verbose_name='QQ号绑定标志'),
        ),
        migrations.AddField(
            model_name='account',
            name='qq_openid',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='QQopenid'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='account',
            name='tel_binding_flag',
            field=models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=256, null=True, verbose_name='手机号绑定标志'),
        ),
        migrations.AddField(
            model_name='account',
            name='wechat_binding_flag',
            field=models.CharField(blank=True, choices=[('Y', '是'), ('N', '否')], max_length=256, null=True, verbose_name='微信绑定标志'),
        ),
        migrations.AddField(
            model_name='account',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='微信openid'),
        ),
    ]
